#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt steeef

eval "$(rbenv init -)"

alias wrk2='~/tools/wrk2/wrk'

export PATH=$PATH:$HOME/tools/omnetpp-5.0/bin

export JAVA_HOME=`/usr/libexec/java_home -v1.8`
